image: 'thlmylab/swakkd:stable'

stages:
  - prepare
  - build
  - deploy
  - expose

variables:
  NS: "mylab-ai-services"

secrets:
  stage: prepare
  script:
    - kubectl create ns $NS || true
    - kubectl delete secret gitlab-registry-$CI_PROJECT_ID -n $NS || true
    - >
      kubectl create secret docker-registry gitlab-registry-$CI_PROJECT_ID
      --docker-server=$CI_REGISTRY
      --docker-username=$CI_DEPLOY_USER
      --docker-password=$CI_DEPLOY_TOKEN
      -n $NS
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"

fast-openai-api-proxy-img:
  stage: build
  image: docker:24
  services: [ "docker:24-dind" ]
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
      changes:
        - '**/*.py'
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/fast-openai-api-proxy:latest -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE/fast-openai-api-proxy:latest

fast-openai-api-proxy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
      changes:
        - '**/*.py'
        - deploy/fast-openai-api-proxy-dep+svc.yaml
  script:
    - cd deploy
    - mo fast-openai-api-proxy-dep+svc.yaml | kubectl delete -n $NS -f - || true
    - mo fast-openai-api-proxy-dep+svc.yaml | kubectl apply -n $NS -f -

fast-openai-api-proxy-ingress:
  stage: expose
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
  script:
    - cd deploy
    - mo project-ing.yaml | kubectl delete -n $NS -f - || true
    - mo project-ing.yaml | kubectl apply -n $NS -f -
